### ISSUE TITLE
support for front-matter

### ISSUE THREAD

**Issue by tami5** [ikatyang/tree-sitter-markdown#21]
Hey @ikatyang, 

Is it possible to support identification of front-matter block. I'd like to inject yaml to it like 

```
(fenced_code_block
  (info_string) @language
  (code_fence_content) @content)
```

Currently I'm getting for 

```
---
title: GitHub Flavored Markdown
author: GitHub
---

```
 
= 
```
thematic_break [0, 0] - [0, 3]
setext_heading [1, 0] - [3, 3]
  heading_content [1, 0] - [2, 14]
    text [1, 0] - [1, 31]
    soft_line_break [1, 31] - [2, 0]
    text [2, 0] - [2, 14]
  setext_heading_underline [3, 0] - [3, 3]

```

Thanks

**Comment by ikatyang** [comment]
I'm not sure what did you meant by injecting yaml, but according to [Multi-language Documents](https://tree-sitter.github.io/tree-sitter/using-parsers#multi-language-documents), there should be a `front-matter` language to be used for extracting the `yaml` part and the `markdown` part, and those extracted parts should be passed to the corresponding language to get the final tree then.

**Comment by tami5** [comment]
Hey @ikatyang I meant more as a simple identification because the syntax tree of ---\frontmatter\--/ is wrong. 

I'll look into multiple languages, i'm getting started with treesitter, feel free to close the issue if it doesn't make sense to identify frontmatter block like code_block

**Comment by ikatyang** [comment]
> the syntax tree of ---\frontmatter--/ is wrong.

That's the expected syntax tree for parsers that follow [CommonMark](https://spec.commonmark.org/current/)/[GFM](https://github.github.com/gfm/) spec strictly, [front matter](https://jekyllrb.com/docs/front-matter/) is not part of the spec but an common extension to the Markdown language, and as far as I can tell there is no spec for how to parse it, its grammar is all up to the implementer.

> feel free to close the issue if it doesn't make sense to identify frontmatter block like code_block

Since front matter is not part of the spec and it could also be used in other languages such as [HTML](https://github.com/tree-sitter/tree-sitter/blob/da5dcba86e5b7ecb7bb3f3b6a3c3e85787a3110a/docs/section-7-playground.html#L1-L5), I think it'd be better to use a `front-matter` language to achieve this goal. I'm going to close this issue but feel free to comment if you have further questions.
