### ISSUE TITLE
Avoid crash

### ISSUE THREAD

**Issue by ikatyang** [ikatyang/tree-sitter-markdown#24]
Context: https://github.com/nvim-treesitter/nvim-treesitter/issues/872#issuecomment-770395213

**Comment by David-Else** [comment]
It would be great to get those segfaults gone to allow treesitter fenced language highlighting in Neovim! Sorry I don't program C++ :(

https://github.com/nvim-treesitter/nvim-treesitter/issues/1126#issuecomment-812166109

**Comment by aktau** [comment]
Sub-syntaxes in fenced code blocks sound awesome. Though my main interest in having an actual good parser for Markdown syntax in Neovim. Due to the length of some fenced blocks, the current regex parser gets really confused a lot. Thanks for writing this parser @ikatyang, looking forward to getting it crash-free enough.
